apiVersion: v1
kind: Service
metadata:
  name: observability-demo-service
  labels:
    app: observability-demo
spec:
  type: ClusterIP
  selector:
    app: observability-demo
  ports:
    - name: http-metrics
      port: 5000
      targetPort: 5000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: observability-demo-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: observability-demo
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
